# Generated by Django 6.0.7 on 2026-08-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data do evento')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='img/eventos/', verbose_name='Imagem')),
                ('publicado', models.BooleanField(default=False, help_text='Controla se o evento aparece no site.', verbose_name='Publicado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.TextField(help_text='Texto curto exibido nos cards de notícia.', verbose_name='Resumo')),
                ('categoria', models.CharField(blank=True, help_text="Selo exibido sobre a notícia (ex.: 'Saúde Digital Piraí').", max_length=60, verbose_name='Categoria')),
                ('imagem', models.ImageField(help_text='Imagem principal da notícia, usada também no carrossel da Home.', upload_to='img/noticias/', verbose_name='Imagem')),
                ('data_publicacao', models.DateTimeField(verbose_name='Data de publicação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('publicada', models.BooleanField(default=False, help_text='Controla se a notícia aparece no site.', verbose_name='Publicada')),
                ('destaque_carrossel', models.BooleanField(default=False, help_text='Exibe esta notícia no carrossel principal da Home.', verbose_name='Destaque no carrossel')),
                ('link_externo', models.URLField(blank=True, help_text='Opcional. Use quando a notícia aponta para um link fora do site.', verbose_name='Link externo')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descricao', models.TextField(help_text='Texto curto exibido no card, na Home.', verbose_name='Descrição')),
                ('icone', models.CharField(default='🏥', help_text='Um emoji para representar o serviço (ex.: 🏥, 🩺, 🚑, 🧠, 🧪).', max_length=10, verbose_name='Ícone')),
                ('link', models.CharField(help_text='Para onde o card leva ao ser clicado. Pode ser um endereço interno do site (ex.: /unidades/) ou um link externo completo (ex.: https://www.netlaudo.com.br/...).', max_length=300, verbose_name='Link')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Cards com número menor aparecem primeiro.', verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, help_text='Controla se o card aparece na Home.', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('Hospital', 'Hospital'), ('Unidade de Saúde da Família', 'Unidade de Saúde da Família'), ('Unidade de Saúde', 'Unidade de Saúde'), ('Centro Especializado', 'Centro Especializado'), ('Pronto Socorro', 'Pronto Socorro'), ('Serviço Especializado', 'Serviço Especializado'), ('Vigilância em Saúde', 'Vigilância em Saúde')], max_length=40, verbose_name='Tipo')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('ativa', models.BooleanField(default=True, help_text='Controla se a unidade aparece na listagem pública.', verbose_name='Ativa')),
                ('imagem', models.ImageField(blank=True, help_text='Opcional. Se não for enviada, o site mostra um ícone padrão conforme o tipo da unidade.', null=True, upload_to='img/unidades/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
    ]
